//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int IdAsistencia { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraIngreso { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
