//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessWebApi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCMProdEntities : DbContext
    {
        public BCMProdEntities()
            : base("name=BCMProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimentacion> Alimentacion { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<Catering> Catering { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Codigo> Codigo { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<Salud> Salud { get; set; }
        public virtual DbSet<Transporte> Transporte { get; set; }
        public virtual DbSet<Transportista> Transportista { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
