//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigo
    {
        public int id_codigo { get; set; }
        public string grupo { get; set; }
        public string subgrupo { get; set; }
        public string elemento { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> valor1 { get; set; }
        public Nullable<decimal> valor2 { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public string fecha_mod { get; set; }
    }
}
