//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public int id_colaborador { get; set; }
        public int sucursal { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string cargo { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public string usuario { get; set; }
        public string fecha_mod { get; set; }
    }
}
