//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planes
    {
        public int id_plan { get; set; }
        public int fk_id_cliente { get; set; }
        public int sucursal { get; set; }
        public string tipo_plan { get; set; }
        public string fecha_inicio_plan { get; set; }
        public string pagado { get; set; }
        public int max_dia_plan { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public string usuario { get; set; }
        public string fecha_mod { get; set; }
    }
}
